### ISSUE TITLE
Remove lerna

### ISSUE THREAD

**Issue by promaty** [aragonone/court-backend#215]
We could remove lerna and use `yarn` `yarn version` for updating our packages.

**Comment by promaty** [comment]
@facuspagnuolo after some testing I prefer to keep lerna. It is much smarter about version management for multiple packages.
- yarn version cannot give you a preview of all package versions when running at the top
- yarn version cannot easily release different tags for different packages, this requires extra scripts
- I see we use lerna in most other monorepos so everyone is probably used to it already

**Comment by promaty** [comment]
- lerna run at the top can create a dependency tree and execute commands in order (e.g. lerna run build will make sure that shared package is built first before trying others that depend on it)

**Comment by sohkai** [comment]
Good to know, let's keep using lerna in these monorepos that should be versioned together :).

To be honest, we only used lerna in the past because npm did not natively provide functionality to manage them (really, only sharing dependencies). Now with yarn and npm both including support for workspaces, there's much less reason to go to lerna unless there's a specific workflow needed (e.g. versioning).
