### ISSUE TITLE
App: add stats in /jurors

### ISSUE THREAD

**Issue by izqui** [aragonone/court-backend#29]
Some stats to consider:

- Total jurors
- Number of active jurors
- Accounts with inactive ANJ (likely hard to get as I am not sure whether we are reducing ANJ state)

**Comment by bingen** [comment]
What do you mean here?
> Accounts with inactive ANJ (likely hard to get as I am not sure whether we are reducing ANJ state)
Do you mean accounts that never got to stake on the registry? Otherwise it would be just the difference from the two ones above, right? (As I guess you mean the number)
In that case I'm not sure this would be the best place to be, I think I would add a summary section to `/anj-balances` too.
